[package]
name = "cdtk_lua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasteval = "0.2.4"
mlua = {version = "0.8.3", features = ["luajit", "vendored"]}
